# Generated by Django 5.1.3 on 2024-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postLikedId', models.CharField(max_length=100)),
                ('postLikedBy', models.CharField(max_length=100)),
            ],
        ),
    ]
