# Generated by Django 5.1.3 on 2024-12-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_likerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likerelation',
            name='postLikedId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post'),
        ),
    ]
