# Generated by Django 5.1.3 on 2024-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_commentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicOfTheSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d')),
                ('imageName', models.CharField(max_length=100)),
            ],
        ),
    ]
